print("Welcome to the File Wizard")
print("The File Wizard will check the type of a file extension and give you details about the extension")
print("\n")
print("\n")
extens = input("Enter the extension of the file:\n")
